### ISSUE TITLE
🐛 Bug Report: StackTrace errors when creating attirbutes

### ISSUE THREAD

**Issue by Caryntjen** [appwrite/sdk-for-kotlin#16]
### 👟 Reproduction steps

When I try call createEnumAttribute from server when the collection exists I get a stacktrace error, similar things happen to Floats. (Integer, Boolean, URL and Email work; IP not tested) 

For example:
`        database.createEnumAttribute(collectionId = "xxxxxx", key = "enumTest", elements = arrayListOf("OPTION"), required = false, default = "OPTION")
      database.createFloatAttribute(collectionId = "xxxxxx", key = "floatTest", min = "0.00", required = false, default = "0.00")
`
(String also has issues but is fixed in 0.2.2 I guess? -> https://github.com/appwrite/sdk-for-kotlin/commit/29c138e92b2f8bf8e626303a9feab44a5555e39d )

### 👍 Expected behavior

The attributes can be created through server code.

### 👎 Actual Behavior

**Stacktrace for Enums, Floats:**
`Exception in thread "OkHttp Dispatcher" java.lang.reflect.InaccessibleObjectException: Unable to make field private java.lang.String java.lang.Throwable.detailMessage accessible: module java.base does not "opens java.lang" to unnamed module @6b0c2d26
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at com.google.gson.internal.reflect.UnsafeReflectionAccessor.makeAccessible(UnsafeReflectionAccessor.java:44)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:159)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.Gson.fromJson(Gson.java:931)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at io.appwrite.Client$awaitResponse$2$1.onResponse(Client.kt:371)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)`

**Stacktrace for String (but fixed in v0.2.2):**
`Exception in thread "OkHttp Dispatcher" java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.String (java.lang.Long and java.lang.String are in module java.base of loader 'bootstrap')
	at io.appwrite.models.AttributeString$Companion.from(AttributeString.kt:20)
	at io.appwrite.services.Database$createStringAttribute$convert$1.invoke(Database.kt:566)
	at io.appwrite.services.Database$createStringAttribute$convert$1.invoke(Database.kt:565)
	at io.appwrite.Client$awaitResponse$2$1.onResponse(Client.kt:363)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
`

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Windows

### 🧱 Your Environment

- appwrite 0.12.1
- io.appwrite:sdk-for-kotlin:0.2.0

other dependencies:
    implementation 'org.jetbrains.kotlin:kotlin-reflect:1.6.10'
    implementation 'org.jetbrains.kotlin:kotlin-stdlib:1.6.10'
    implementation "io.appwrite:sdk-for-kotlin:0.2.0"
    implementation "com.sun.xml.bind:jaxb-impl:3.0.2"
    implementation 'org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.2'
    implementation "org.apache.logging.log4j:log4j-api-kotlin:1.1.0"
    implementation 'org.apache.logging.log4j:log4j-api:2.17.1'
    implementation 'org.apache.logging.log4j:log4j-core:2.17.1'
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.0"
    implementation "com.fasterxml.jackson.module:jackson-module-kotlin:2.13.1"

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Caryntjen** [comment]
@abnegate Just to make it clear as I could test v0.2.2. The String error was fixed but the Enum and Float errors are not. Hopefully you find a solution.

**Comment by Caryntjen** [comment]
@abnegate I have encounterted the same error when trying to create Team Memberships.

So lets say I have created a team with the follow id: MY_TEAM and I want to add a team membership through the server.

```
     val adminMembership = appwriteTeams.createMembership(
            teamId = "MY_TEAM",
            email = "user@test.com",
            roles = listOf("user"),
            url = "http://localhost/",
            name = "TEST USER"
        )
```

I do get the same error:

```
Exception in thread "OkHttp Dispatcher" java.lang.reflect.InaccessibleObjectException: Unable to make field private java.lang.String java.lang.Throwable.detailMessage accessible: module java.base does not "opens java.lang" to unnamed module @382db087
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at com.google.gson.internal.reflect.UnsafeReflectionAccessor.makeAccessible(UnsafeReflectionAccessor.java:44)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:159)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.Gson.fromJson(Gson.java:931)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at io.appwrite.Client$awaitResponse$2$1.onResponse(Client.kt:371)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Caryntjen** [comment]
Okay the project had JAVA v17 and could not show the propper appwrite Exception, so I have lowered the JAVA API and it shows the proper error messages.

**Comment by abnegate** [comment]
@Caryntjen Thank you for the info! A fix is underway :grin:

**Comment by Caryntjen** [comment]
@abnegate thank you. I am eagerly awaiting the fixes because they are blocking my projet. 

I saw a snapshot release with the fixes in: https://github.com/appwrite/sdk-for-kotlin/releases/tag/0.2.4-SNAPSHOT 

Is that suppose to be in Maven Central repo because it seems like it is not?
