### ISSUE TITLE
Wrong response type when creating document

### ISSUE THREAD

**Issue by OKatrych** [appwrite/sdk-for-kotlin#24]
`database.createDocument` returns `DocumentList` object response but the SDK waits for `Document` object response.

Error when executing `database.createDocument`:
```
Exception in thread "OkHttp Dispatcher" java.lang.NullPointerException: null cannot be cast to non-null type kotlin.String
	at io.appwrite.models.Document$Companion.from(Document.kt:42)
	at io.appwrite.services.Database$createDocument$converter$1.invoke(Database.kt:770)
	at io.appwrite.services.Database$createDocument$converter$1.invoke(Database.kt:769)
	at io.appwrite.Client$awaitResponse$2$1.onResponse(Client.kt:472)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

The same issue is present on the Android SDK side.

**Comment by abnegate** [comment]
@OKatrych Closing as this should not be an issue with Appwrite 0.15 and Kotlin SDK 0.6.0. Please re-open if your issue persists :grin:
